apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    app: django
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
        env: test
    spec:
      containers:
      - name: django
        imagePullPolicy: Always
        image: localhost:32121/###USER###/django-pipeline/django:###TAG###
        ports:
        - containerPort: 8000
      imagePullSecrets: 
      - name: gitcred
